/*
 * Autogenerated header file: lut.h
 */

#ifndef OTHELLO_LUT
#define OTHELLO_LUT

/*
 * TYPES
 */

typedef struct
{
  unsigned int mask[2];
  unsigned int color[2];
}Othello_LUT;


/*
 * VARIABLES
 */

extern unsigned int othello_LUTOffset[128];
extern Othello_LUT othello_LUT[1036];

#endif  /* OTHELLO_LUT */
