/*
 * Autogenerated header file: lut64.h
 */

#ifndef OTHELLO_LUT
#define OTHELLO_LUT

/*
 * TYPES
 */

typedef struct
{
  unsigned long mask;
  unsigned long color;
}Othello_LUT;


/*
 * VARIABLES
 */

extern unsigned int othello_LUTOffset[128];
extern Othello_LUT othello_LUT[1036];

#endif  /* OTHELLO_LUT */
